site_name: Eternal Beta Wiki
repo_url: https://github.com/Kacianoki/Eternal-Beta-Wiki
copyright: Copyright (c) 2025 Kacianoki

exclude_docs: overrides/
docs_dir: docs/

theme:
  name: material
  custom_dir: docs/overrides
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      accent: deep purple
      primary: black
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      accent: deep purple
      primary: black
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  logo: assets/logo.png

markdown_extensions:
  - pymdownx.highlight:
      linenums: true
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - admonition


nav:
  - Home: index.md
  - ELua: 
    - Guides:
      - Intro: elua/guides/intro.md
      - Execution context: elua/guides/exec-context.md
      - API Basics:
        - Intro: elua/guides/api-basics/intro.md
        - system_console: elua/guides/api-basics/system-console.md
        - system_io: elua/guides/api-basics/system-io.md
        - system: elua/guides/api-basics/system.md
    - Namespaces:
      - List: elua/namespaces/list.md
      - system: elua/namespaces/system.md
      - system_console: elua/namespaces/system_console.md
      - system_io: elua/namespaces/system_io.md
      - system_monitors: elua/namespaces/system_monitors.md
      - system_text_json: elua/namespaces/system_text_json.md
      - system_text_regex: elua/namespaces/system_text_regex.md

plugins:
  - search
  - i18n:
      docs_structure: folder
      languages:
        - locale: en
          default: true
          name: English
          build: true
        - locale: ru
          name: Русский
          build: true
          nav_translations:
            Home: Домашняя страница
            Guides: Гайды
            Intro: Введение
            Execution context: Контекст выполнения
            API Basics: Основы API
            Namespaces: Пространства имён
            List: Список
