name: deploy

on:
  push:
     branches: [ main ]
     paths:
      - '**.md'
      - '**.yml'
      - '**.js'
      - '**.html'
      - '**.css'
      - '**.txt'

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-lastet
    permissions:
      contents: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        submodules: true

    - name: Deploy
      run: |
        chmod +x deploy.sh
        ./deploy.sh
  
      
